apiVersion: broker.amq.io/v1beta1
kind: ActiveMQArtemis
metadata:
  name: artemis-broker
spec:
  deploymentPlan:
    size: 2
    requireLogin: true
    persistenceEnabled: true
    journalType: nio
    messageMigration: true
    storage:
      size: 1Gi
    resources:
      limits:
        cpu: "1000m"
        memory: "2Gi"
      requests:
        cpu: "1000m"
        memory: "2Gi"
  console:
    expose: true
  acceptors:
    - name: core
      port: 61616
      protocols: core
    - name: core-tls
      port: 61617
      protocols: core
      expose: true
      sslEnabled: true
      sslSecret: artemis-broker-tls-secret
    - name: amqp
      port: 5672
      protocols: amqp
    - name: amqp-tls
      port: 5673
      protocols: amqp
      expose: true
      sslEnabled: true
      sslSecret: artemis-broker-tls-secret
  addressSettings:
    applyRule: merge_all
    addressSetting:
      - match: "#"
        redistributionDelay: 5000
  brokerProperties:
    - "globalMaxSize=1GiB"
    - "clusterConfigurations.my-cluster.messageLoadBalancingType=OFF_WITH_REDISTRIBUTION"
    - "connectorConfigurations.dc2-federation-connector.params.host=${DC2_HOST}"
    - "connectorConfigurations.dc2-federation-connector.params.port=${DC2_PORT}"
    - "connectorConfigurations.dc2-federation-connector.params.sslEnabled=true"
    - "connectorConfigurations.dc2-federation-connector.params.trustStorePath=/etc/artemis-broker-tls-secret-volume/client.ts"
    - "connectorConfigurations.dc2-federation-connector.params.trustStorePassword=password"
    - "federationConfigurations.dc1-to-dc2.credentials.user=${DC2_USER}"
    - "federationConfigurations.dc1-to-dc2.credentials.password=${DC2_PASS}"
    - "federationConfigurations.dc1-to-dc2.upstreamConfigurations.dc2.connectionConfiguration.staticConnectors=dc2-federation-connector"
    - "federationConfigurations.dc1-to-dc2.upstreamConfigurations.dc2.connectionConfiguration.retryInterval=500"
    - "federationConfigurations.dc1-to-dc2.upstreamConfigurations.dc2.connectionConfiguration.retryIntervalMultiplier=2"
    - "federationConfigurations.dc1-to-dc2.upstreamConfigurations.dc2.connectionConfiguration.maxRetryInterval=30000"
    - "federationConfigurations.dc1-to-dc2.upstreamConfigurations.dc2.connectionConfiguration.circuitBreakerTimeout=30000"
    - "federationConfigurations.dc1-to-dc2.upstreamConfigurations.dc2.policyRefs=app-qp"
    - "federationConfigurations.dc1-to-dc2.queuePolicies.app-qp.includeFederated=false"
    - "federationConfigurations.dc1-to-dc2.queuePolicies.app-qp.includes.all-app.queueMatch=app.#"
